formula = formula , '<->' , formula
        | formula , '->' , formula
        | formula , '+' , formula
        | formula , '*' , formula
        | '!' , formula
        | '(' , formula , ')'
        | literal
        ;

literal = ?[A-Za-z]+? ;
